using System.Net.Mail;
using System.Net;
using Microsoft.AspNetCore.DataProtection.KeyManagement;
using Amazon.SecretsManager;
using Amazon;
using Amazon.SecretsManager.Model;
using Amazon.Runtime;
using System.Runtime.Intrinsics.X86;
//using Amazon.SecretsManager.Extensions.Caching;

namespace StaticFileSecureCall.Services
{
    /// <summary>
    ///********Key Generation Algorithm developed by Austin.
    ///********Further updates to be considered.
    /// </summary>
    public class KeyMaster : IKeyGenerator
    {
        private readonly string randomString;
        private readonly string name;
        private readonly ILogger<KeyMaster> _logger;
        public KeyMaster(ILogger<KeyMaster> logger)
        {
            randomString = GenerateRandomString();
            name = $"request{DateTime.Now:HH:mm:ss}";
            _logger = logger;
        }

        private async Task SendGeneratedKey()
        {
            string smtpHost = "smtp.gmail.com";
            //int smtpPort = 465;  // Using port 465 to ensure SSL/TLS is configured.
            int smtpPort = 587;
            //string smtpUsername = RetrieveKeyAsync().Result[1];
            //string smtpPassword = RetrieveKeyAsync().Result[0];
            string smtpUsername = "info.kygosystems@gmail.com";
            string smtpPassword = "$**********";
            bool enableSsl = true;
            string[] recipientEmails = { "subzbelow@gmail.com", "kdonaldresources@gmail.com", "abtesting911@gmail.com" };

            // Create SMTP client
            using (SmtpClient smtpClient = new SmtpClient(smtpHost, smtpPort))
            {
                smtpClient.UseDefaultCredentials = false;
                smtpClient.Credentials = new NetworkCredential(smtpUsername, smtpPassword);
                smtpClient.EnableSsl = enableSsl;
                //smtpClient.Security
                foreach (string recipientEmail in recipientEmails)
                {
                    // Create the email message
                    MailMessage mailMessage = new MailMessage
                    {
                        From = new MailAddress(smtpUsername),
                        Subject = $"[Autogenerated]Secret Key and Name at {DateTime.Now.ToString(@"dddd")}, {DateTime.Now.ToString(@"dd")} " +
                        $"{DateTime.Now:HH:mm:ss}",
                        Body = $"Hi there,\n here's your Name and Secret respectively;\n Name: {name}\n Secret: {randomString} done securely with SSH/TLS" +
                        $"note that secrets refresh every 1 hour." +
                        $"\n\n\n regards Austin.live.ai.",
                        IsBodyHtml = false
                    };
                    //smtpClient
                    mailMessage.To.Add(recipientEmail);
                    try
                    {
                        await smtpClient.SendMailAsync(mailMessage); ;
                        _logger.LogInformation($"Email sent successfully to {recipientEmail}");
                    }
                    catch (IOException ioex)
                    {
                        _logger.LogError($"Error sending email to {recipientEmail}: {ioex.Message}");
                    }
                    catch (SmtpException smtpex)
                    {
                        _logger.LogError($"Error sending email to {recipientEmail}: {smtpex.Message}");
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError($"Error sending email to {recipientEmail}: {ex.Message}");
                        throw new Exception(ex.Message);
                    }
                    //string smtpHost = Configuration["SmtpConfig:SmtpHost"];
                }
            }
        }

        //KeyGen
        public static string GenerateRandomString(int length = 16)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789£#~&%_-$@?/";
            Random random = new Random();
            return new string(Enumerable.Repeat(chars, length).Select(s => s[random.Next(s.Length)]).ToArray());
        }

        //save to AWS secret Manager.
        public async Task ConfigureKeyAsync()
        {
            SendGeneratedKey();
            AWSCredentials credentials = new BasicAWSCredentials(name, randomString);
            AmazonSecretsManagerClient secretsManagerClient = new AmazonSecretsManagerClient(
                credentials,
                RegionEndpoint.EUWest1 // Determine the best region discussing with Tunde.
            );
            string secretName = name;
            string secretValue = randomString;
            var request = new PutSecretValueRequest
            {
                SecretId = secretName,
                SecretString = secretValue
            };
            PutSecretValueResponse response = await secretsManagerClient.PutSecretValueAsync(request);
            if (response.HttpStatusCode == HttpStatusCode.OK) // Check if the response indicates success
            {
                _logger.LogInformation("Secret successfully deployed from KeyGen to AWS");
            }
            secretsManagerClient.Dispose();
        }

        //retrieve from AWS Secret Manager.
        public async Task<string[]> RetrieveKeyAsync()
        {
            string secretName = "mailpass";
            string secretEmail = "mailname";
            using (var secretsManagerClient = new AmazonSecretsManagerClient(Amazon.RegionEndpoint.USWest2))
            {
                var getRequest = new GetSecretValueRequest
                {
                    SecretId = secretName
                };
                var getRequest1 = new GetSecretValueRequest
                {
                    SecretId = secretEmail
                };
                try
                {
                    var getResponse = await secretsManagerClient.GetSecretValueAsync(getRequest);
                    var getResponse1 = await secretsManagerClient.GetSecretValueAsync(getRequest1);
                    string[] secretValue = new string[2];
                    secretValue[0] = getResponse.SecretString;
                    secretValue[1] = getResponse1.SecretString;
                    _logger.LogInformation("Secrets successfully retrieved.");
                    return secretValue;
                }
                catch (Exception ex)
                {
                    _logger.LogError("Error retrieving secrets: " + ex.Message);
                    throw;
                }
            }
        }
    }
}
//private SecretsManagerCache cache = new SecretsManagerCache();
//public async Task<Response> FunctionHandlerAsync(string input, ILambdaContext context)
//{
//    string MySecret = await cache.GetSecretString(MySecretName);
//    // Use the secret, return success
//}

